# Image légère
FROM python:3.11-slim

# Évite la création de fichiers .pyc et active l'affichage en temps réel
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR /app

# Copier d'abord uniquement le fichier de dépendances
COPY requirements.txt /app/

# Copie de vos fichiers locaux dans le conteneur
COPY ./python /app/

# Installation des dépendances sans cache
RUN pip install --no-cache-dir -r requirements.txt

# Commande par défaut (garde le conteneur ouvert)
CMD ["tail", "-f", "/dev/null"]
