connector.name=iceberg
iceberg.catalog.type=nessie
iceberg.nessie-catalog.uri=http://catalog:19120/api/v2
iceberg.nessie-catalog.ref=main
iceberg.nessie-catalog.default-warehouse-dir=s3://refine-bucket/warehouse
iceberg.file-format=PARQUET
iceberg.compression-codec=SNAPPY
iceberg.security=ALLOW_ALL
fs.native-s3.enabled=true
s3.aws-access-key=admin
s3.aws-secret-key=password123
s3.endpoint=http://minio:9000
s3.path-style-access=true
s3.region=us-east-1
iceberg.bucket-execution=true
iceberg.metadata.parallelism=4
iceberg.idle-writer-min-file-size=10MB
iceberg.remove-orphan-files.min-retention=1d
iceberg.expire-snapshots.min-retention=1d
iceberg.metadata-cache.enabled=true
iceberg.add-files-procedure.enabled=true
iceberg.register-table-procedure.enabled=true
iceberg.projection-pushdown-enabled=true
iceberg.target-max-file-size=20MB
iceberg.max-partitions-per-writer=10
# --- OPTIMISATIONS (Nouveaux noms 479) ---
# Trino 479 a supprimé le préfixe 'fs.native-s3.' pour ces propriétés
s3.max-connections=200
s3.tcp-keep-alive=true
s3.streaming.part-size=5MB

# Gestion des fichiers
iceberg.max-open-sort-files=100
iceberg.writer-sort-buffer-size=128MB
parquet.small-file-threshold=128kB

# Suppression de 'hive.orc.lazy-read-small-ranges' car elle est dépréciée 
# et activée par défaut dans les versions récentes.