connector.name=iceberg
iceberg.catalog.type=rest
iceberg.rest-catalog.uri=http://polaris:8181/api/catalog
iceberg.rest-catalog.warehouse=polaris-bucket/warehouse
iceberg.rest-catalog.vended-credentials-enabled=false
iceberg.rest-catalog.oauth2.server-uri=http://polaris:8181/api/catalog/v1/oauth/tokens
iceberg.rest-catalog.oauth2.token-refresh-enabled=true
iceberg.rest-catalog.oauth2.token-exchange-enabled=true
iceberg.rest-catalog.security=OAUTH2
iceberg.rest-catalog.oauth2.credential=polaris,password
iceberg.rest-catalog.oauth2.scope=PRINCIPAL_ROLE:ALL
iceberg.file-format=PARQUET
iceberg.compression-codec=SNAPPY
iceberg.security=ALLOW_ALL
fs.native-s3.enabled=true
s3.aws-access-key=admin
s3.aws-secret-key=password123
s3.endpoint=http://minio:9000
s3.path-style-access=true
s3.region=us-east-1
iceberg.bucket-execution=true
iceberg.metadata.parallelism=4
iceberg.idle-writer-min-file-size=10MB
iceberg.remove-orphan-files.min-retention=1d
iceberg.expire-snapshots.min-retention=1d
iceberg.metadata-cache.enabled=true
iceberg.add-files-procedure.enabled=true
iceberg.register-table-procedure.enabled=true
iceberg.projection-pushdown-enabled=true
iceberg.target-max-file-size=20MB
iceberg.max-partitions-per-writer=10