name: bigdata_nifi

services:
  db-light:
    image: postgres:16.13-alpine
    container_name: db-light
    hostname: db-light
    #env_file:
    #  - path: docker/.env # default
    #    required: true
    #restart: unless-stopped
    volumes:
      - share_data:/partage
    #  #- db_home_light:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 5s # Laisse du temps pour l'initialisation initiale
    environment:
      POSTGRES_DB: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    command: postgres -c max_connections=10
    networks:
      - bigdata

  # METABASE
  metabase:
    image: metabase/metabase:v0.59.4.3
    container_name: metabase
    hostname: metabase
    #restart: always
    healthcheck:
      test: curl --fail -I http://localhost:3000/api/health || exit 1
      interval: 15s
      timeout: 5s
      retries: 10
      start_period: 15s
    depends_on:
      db-light:
        condition: service_healthy
    ports:
      - 3400:3000
    volumes:
      - share_data:/partage
    #  - /dev/urandom:/dev/random:ro
    environment:
      # APP config
      MB_SITE_NAME: "My Company"
      MB_AUDIT_MAX_RETENTION_DAYS: 1
      MB_CHECK_FOR_UPDATES: false
      MB_INSTALL_ANALYTICS_DATABASE: false
      MB_LOAD_ANALYTICS_CONTENT: false
      MB_MONITOR_PERFORMANCE: false
      MB_LDAP_ENABLED: false      
      MB_SURVEYS_ENABLED: false  
      MB_NO_SURVEYS: true 
      MB_LOAD_SAMPLE_CONTENT: true # no examples
      MB_PASSWORD_COMPLEXITY: weak
      MB_START_OF_WEEK: monday
      MB_PERSISTED_MODELS_ENABLED: true
      MB_PERSISTED_MODEL_REFRESH_CRON_SCHEDULE: 0 0 0/1 * * ? *
      MB_ANON_TRACKING_ENABLED: false
      # resources manager
      JAVA_OPTS: -Xmx512m -Xms256m
      MB_JETTY_MAXTHREADS: 20   # Réduit de 50 à 15 (suffisant pour 1-3 utilisateurs)
      MB_JETTY_MINTHREADS: 2    # Minimum de threads au repos
      MB_DB_CONNECTION_TIMEOUT_MS: 30000 # Évite les crashs si la DB est lente
      # if you want to use postgres instead of H2
      #MB_DB_TYPE: h2  # Pour test uniquement, utilisez Postgres en prod
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: postgres
      MB_DB_PORT: 5432
      MB_DB_USER: postgres
      MB_DB_PASS: postgres
      MB_DB_HOST: db-light 
    deploy:
      resources:
        limits:
          memory: 1.5G 
    networks:
      - bigdata

  catalog:
    #https://clickhouse.com/docs/use-cases/data-lake/nessie-catalog
    image: ghcr.io/projectnessie/nessie:0.99.0
    container_name: catalog
    hostname: catalog
    restart: always
    ports:
      - 19720:19120
    depends_on:
      minio:
        condition: service_healthy
      mariadb:
        condition: service_healthy
    volumes:
      - share_data:/partage
    environment:
      # Configuration de Nessie pour utiliser MinIO comme backend de stockage
      # Vous pouvez ajuster ces variables en fonction de votre configuration MinIO
      #- nessie.version.store.type=IN_MEMORY
      - nessie.catalog.default-warehouse=warehouse
      - nessie.catalog.warehouses.warehouse.location=s3://nessie-bucket/warehouse
      - nessie.catalog.service.s3.default-options.endpoint=http://minio:9000/
      - nessie.catalog.service.s3.default-options.access-key=urn:nessie-secret:quarkus:nessie.catalog.secrets.access-key
      - nessie.catalog.service.s3.default-options.path-style-access=true
      - nessie.catalog.service.s3.default-options.auth-type=STATIC
      - nessie.catalog.secrets.access-key.name=admin
      - nessie.catalog.secrets.access-key.secret=password123
      - nessie.catalog.service.s3.default-options.region=us-east-1
      - nessie.server.authentication.enabled=false
      # persistance avec une base de données relationnelle (ex: MySQL/MariaDB)
      # Configuration du stockage
      # 1. Active le stockage persistant via JDBC
      - NESSIE_VERSION_STORE_TYPE=JDBC
      # 2. Définit le dialecte SQL (MariaDB)
      - QUARKUS_DATASOURCE_DB_KIND=mariadb
      - NESSIE_VERSION_STORE_PERSIST_JDBC_DATASOURCE=mariadb # MySQL utilise le driver MariaDB compatible      
      # Configuration de la source de données (Quarkus)
      - QUARKUS_DATASOURCE_MARIADB_JDBC_URL=jdbc:mariadb://mariadb:3306/nessie_metadata
      - QUARKUS_DATASOURCE_MARIADB_USERNAME=mariadb
      - QUARKUS_DATASOURCE_MARIADB_PASSWORD=password
      # 4. Optimisation (Optionnel mais recommandé)
      - QUARKUS_HIBERNATE_ORM_DATABASE_GENERATION=update
    healthcheck:
      test: ["CMD", "curl", "-f", "http://catalog:19120/api/v1/trees"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 20s
    networks:
      - bigdata

  ### USED FOR CATALOG METADATA
  mariadb:
    image: mariadb:10.11
    container_name: mariadb
    hostname: mariadb
    restart: always
    ports:
      - 3316:3306
    environment:
      MARIADB_USER: mariadb
      MARIADB_PASSWORD: password
      MARIADB_DATABASE: nessie_metadata
      MARIADB_ROOT_PASSWORD: mariadb
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - bigdata

  # 4. Moteur de requête SQL Trino
  # coordinator=true (Trino en mode coordonnateur)
  # url: https://trino.io/docs/current/connector/iceberg.html
  # username: trino
  # password: NONE (authentification désactivée pour simplifier la configuration)
  trino:
    image: trinodb/trino:479
    container_name: trino
    hostname: trino
    restart: always
    ports:
      - "18080:8080"
    volumes:
      - ./trino/config:/etc/trino
      - ./trino/config-coordinator.properties:/etc/trino/config.properties:ro
      - ./trino/node-coordinator.properties:/etc/trino/node.properties:ro
      - share_data:/partage
    healthcheck:
      # On teste si l'API Trino répond sur le port 8080
      test: ["CMD", "curl", "-f", "http://trino:8080/v1/info"]
      interval: 10s    # Fréquence du test
      timeout: 5s      # Temps d'attente avant échec
      retries: 10      # Nombre d'essais avant de marquer "unhealthy"
      start_period: 30s # Temps laissé à Trino pour démarrer avant le 1er test
    depends_on:
      catalog:
        condition: service_healthy
    networks:
      - bigdata

  # 4. Moteur de requête SQL Trino
  # coordinator=false (Trino en mode worker)
  trino-worker:
    image: trinodb/trino:479
    container_name: trino-worker
    hostname: trino-worker
    restart: always
    volumes:
      - ./trino/config:/etc/trino
      - ./trino/config-worker.properties:/etc/trino/config.properties:ro
      - ./trino/node-worker-1.properties:/etc/trino/node.properties:ro
      - share_data:/partage
    healthcheck:
      test: ["CMD", "curl", "-f", "http://trino-worker:8081/v1/info"]
      interval: 10s    # Fréquence du test
      timeout: 5s      # Temps d'attente avant échec
      retries: 10      # Nombre d'essais avant de marquer "unhealthy"
      start_period: 30s # Temps laissé à Trino pour démarrer avant le 1er test
    depends_on:
      trino:
        condition: service_healthy
    networks:
      - bigdata

  # delete a bucket:
  # docker exec minio mc rb --force myalias/NOM-DU-BUCKET
  minio:
    image: quay.io/minio/minio:latest
    container_name: minio
    hostname: minio
    ports:
      - "9030:9000" # API S3
      - "9031:9001" # Console Web (UI)
    environment:
      # Access Key (Username) et de Secret Key (Password)
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: password123
    volumes:
      - minio_data:/data
      - share_data:/partage
    entrypoint: ["/bin/sh", "-c"] # On force le shell ici
    command: >
            "minio server /data --console-address ':9001' & 
             sleep 5; 
             mc alias set myalias http://localhost:9000 admin password123;
             wait"
    restart: always
    healthcheck:
      test: ["CMD", "mc", "ready", "local"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 5s
    networks:
      - bigdata   



volumes:
  minio_data:
    driver: local # Define the driver and options under the volume name
    driver_opts:
      type: none
      device: /home/patrick/Téléchargements/ressources/minio
      o: bind
  mariadb_data:
    driver: local # Define the driver and options under the volume name
    driver_opts:
      type: none
      device: /home/patrick/Téléchargements/ressources/mariadb
      o: bind
  share_data:
    driver: local # Define the driver and options under the volume name
    driver_opts:
      type: none
      device: /home/patrick/Téléchargements/ressources/share_folder
      o: bind
#  db_home_light:
#    external: false

networks:
  bigdata:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: bigdata_bridge